name: Build/release

on:
  push:
    branches:
      - master
      
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Ajusta la versión de Node.js según tus necesidades

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Ajusta la versión de Python según tus necesidades

      - name: Install Dependencies
        run: npm ci

      - name: Get App Version
        id: get_version
        run: echo "::set-output name=app_version::$(node -e 'console.log(require("./package.json").version)')"

      - name: Build Electron app
        uses: electron-userland/electron-builder-action@v2
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # Set the version of the app to the one obtained from package.json
          build_version: ${{ steps.get_version.outputs.app_version }}
